apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::200901485389:role/system-eks-node-group-20260120050628486100000003
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2026-01-20T05:18:15Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1113"
  uid: 00c3df8a-ea0d-484c-bc50-5d31e0a2d172
