apiVersion: v1
data:
  mapRoles: |
    - rolearn: arn:aws:iam::200901485389:role/system-eks-node-group-20260119165947621000000001
      groups:
      - system:bootstrappers
      - system:nodes
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2026-01-19T17:11:54Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "1071"
  uid: 772c4283-fae4-4785-adbb-72bfaa3d3533
