global:
  nodeSelector:
    workload: app-infra

  tolerations:
    - key: "node.kubernetes.io/instance-type"
      operator: "Exists"
      effect: "NoSchedule"

  affinity:
    nodeAffinity:
      type: hard
      matchExpressions:
        - key: workload
          operator: In
          values:
            - app-infra

server:
  nodeSelector:
    workload: app-infra
  ingress:
    enabled: false
    ingressClassName: nginx
    path: /
    pathType: Prefix
    annotations:
      nginx.ingress.kubernetes.io/ssl-redirect: "false"

repoServer:
  nodeSelector:
    workload: app-infra

controller:
  nodeSelector:
    workload: app-infra

applicationSet:
  nodeSelector:
    workload: app-infra

configs:
  cm:
    url: http://a76395855ddc34bee82132a8026b25f5-1988455097.us-east-1.elb.amazonaws.com
  params:
    server.insecure: true
    server.basehref: /
