global:
  nodeSelector:
    role: app

server:
  ingress:
    enabled: true
    ingressClassName: nginx

    hosts:
      - ""

    paths:
      - /argocd(/|$)(.*)

    annotations:
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/rewrite-target: /$2

  extraArgs:
    - --insecure

configs:
  params:
    server.rootpath: /argocd
    server.basehref: /argocd
