apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-sample
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-sample
  template:
    metadata:
      labels:
        app: nginx-sample
    spec:
      containers:
      - name: nginx
        image: public.ecr.aws/nginx/nginx:stable-perl
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-sample-service
spec:
  type: LoadBalancer
  selector:
    app: nginx-sample
  ports:
  - port: 80
    targetPort: 80
