apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-app
  namespace: default
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx-app
  template:
    metadata:
      labels:
        app: nginx-app
    spec:
      containers:
      - name: nginx
        image: public.ecr.aws/nginx/nginx:stable-perl
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginx-config
          mountPath: /etc/nginx/conf.d
      - name: nginx-exporter
        image: nginx/nginx-prometheus-exporter:1.1.0
        args:
          - -nginx.scrape-uri=http://127.0.0.1/stub_status
        ports:
        - name: metrics
          containerPort: 9113
      volumes:
      - name: nginx-config
        configMap:
          name: nginx-app-config
