apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: app-infra
spec:
  amiFamily: AL2023

  amiSelectorTerms:
    - alias: al2023@latest

  role: system-eks-node-group-20260226064732064800000003

  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "test-eks"

  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "test-eks"

  userData: |
    MIME-Version: 1.0
    Content-Type: multipart/mixed; boundary="==MYBOUNDARY=="

    --==MYBOUNDARY==
    Content-Type: text/x-shellscript; charset="us-ascii"

    #!/bin/bash
    set -ex

    /etc/eks/bootstrap.sh test-eks \
      --kubelet-extra-args '--node-labels=Role=app' \
      --container-runtime containerd

    --==MYBOUNDARY==--

  tags:
    Intent: "ApplicationWorkload"
    workload: "app"
    role: "app"
